USE DATABASE testdb
CREATE DATABASE testdb
CREATE TABLE CATEGORY (id int,name null)
INSERT INTO CATEGORY VALUES (1 ,admin )

USE DATABASE testdb
CREATE DATABASE testdb
CREATE TABLE USERS (id int,name null)
INSERT INTO USERS VALUES (1 ,parthshah )
INSERT INTO USERS VALUES (2 ,Vraj )
INSERT INTO USERS VALUES (3 ,Viren )
INSERT INTO USERS VALUES (4 ,Rahul )
INSERT INTO USERS VALUES (5 ,abcd )

